id: AFCC0F709
title: 'Cloud-Banks of the Two Accumulations: A Feast Offering Including the Six Vajra
  Lines Prayer to Be Practiced with Any Guru Sādhana'
type: translation
pechas:
- ID1A664FA
- I89B1F84E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:13.969595
  last_modified_at: 2023-01-04 11:34:13.969609
  collections:
  - Chokling Tersé Tulku
  - Works of Tibetan Masters
alignment_to_base:
  ID1A664FA/893B: 8FDF
  I89B1F84E/FFFA: 8FDF
